blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('detalhes/<int:pk>/<slug:slug>', views.detail, name="details"),
    path('post/novo/', views.post, name="new_post"),
    path('editar/post/<int:pk>', views.edit, name="edit"),
    path('filter/<int:pk>/<str:username>', views.filter, name="filter"),
    path('search/', views.search, name="search"),
    path('delete/<int:pk>', views.delete, name="delete_post"),
    path('contato/', views.contato, name="contato"),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('registro/', views.register_view, name="register"),
    path('registro/criar/', views.register_create, name="register_create"),
    path('login/', views.login_view, name="login"),
    path('login/criar/', views.login_create, name="login_create"),
    path('logout/', views.logout_view, name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
]

login/models.py
from django.db import models

# Create your models here.

login/forms/login.py
from django import forms

from utils.django_forms import add_placeholder


class LoginForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Escreva seu usuário')
        add_placeholder(self.fields['password'], 'Escreva sua senha')

    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

login/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from utils.django_forms import (add_placeholder, strong_password, validate_len,
                                validate_number, validate_symbol,
                                validate_upper)


class RegisterForm(forms.ModelForm):

    # Forma 3
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Seu usuário')
        add_placeholder(self.fields['email'], 'Ex.: email@gmail.com')
        add_placeholder(self.fields['first_name'], 'Ex.: João')
        add_placeholder(self.fields['last_name'], 'Ex.: Alves')

    # Forma 2
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Digite a sua senha'}),
        error_messages={'required': 'Senha não pode ser vazia'},
        # help_text=('A senha precisa ter uma letra maiúscula, '
        #            'uma letra minúscula e números.'
        #            'Precisa ter no mínimo 8 caracteres'),
        validators=[validate_upper, validate_symbol,
                    validate_number, strong_password, validate_len]
    )

    confirm_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Confirme a sua senha'}),
        error_messages={'required': 'Senha não pode ser vazia'}
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password',]

        labels = {
            'username': 'Usuário',
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'email': 'E-mail',
            'password': 'Senha',
            'confirm_password': 'Confirmar senha',
        }

    # validação do campo, caso ele entre na condição, ele envia um alerta
    def clean_password(self):

        data = self.cleaned_data.get('password')

        if 'aten' in data:
            raise ValidationError(
                'Não digite %(value)s no campo',
                code='Invalid',
                params={'value': '"aten"'}
            )

        return data

    # Verificação para ver se os password são iguais
    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError({
                'password': 'As senhas precisam se iguais',
                'confirm_password': 'As senhas precisam se iguais'
            })

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()

        if exists:
            raise ValidationError(
                'O e-mail informado já está em uso. Tente outro')

        return email

login/forms/user_update.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User


class EditUserProfileForm(UserChangeForm):

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': "Enter uour username"}))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Enter your first name"}))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Enter your last name"}))

    username = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Enter your last name"}))

    class Meta:
        model = User
        fields = ['username', 'first_name', "last_name", 'email']

login/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import Http404
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.translation import gettext as _

from blog.models import Post

from .forms import LoginForm, RegisterForm
from .tokens import account_activation_token


def activateEmail(request, user, to_email):
    mail_subject = _(f'Ativação de conta - {user.username}')
    message = render_to_string('login/template_activate_account.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, _(f'<strong>{user}</strong>, vá por favor para o \
                         seu email: <strong>{to_email}</strong> e click no \
            link recebido para confirmar e completar o seu registro.<br>\
                         <strong>Nota:</strong>\
                          Verifique a sua caixa de spam.'))
    else:
        messages.error(
            request, _(f'problema ao enviar o email de confirmação para \
                {to_email}, verifique se o e-mail foi digitado corretamente.'))


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(
            request, _('Obrigado por confirmar o seu e-mail. Agora você pode\
                  fazer o login na sua conta.'))
        return redirect('login:login')
    else:
        messages.error(request, _('O link de ativação é válido'))

    return redirect('blog:index')


def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    forms = RegisterForm(register_form_data)
    return render(request, "login/register_user.html", {
        'forms': forms,
        'form_action': reverse('login:register_create')})


def register_create(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.is_active = False
        user.save()
        activateEmail(request, user, form.cleaned_data.get('email'))

        del (request.session['register_form_data'])
        return redirect(reverse('login:login'))

    messages.error(request, _('Erro ao criar a conta'))

    return redirect('login:register')


def login_create(request):

    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)
    login_url = reverse('login:login')

    if form.is_valid():

        authenticate_user = authenticate(

            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticate_user is not None:
            messages.success(request, _('Você está logado'))
            login(request, authenticate_user)
            return redirect(login_url)
        if not request.user.is_active:
            messages.error(
                request, _('Sua conta ainda não foi ativada'))
            return redirect(login_url)
        messages.error(request, _('Credenciais inválidas'))
        return redirect(login_url)
    messages.error(request, _('Erro ao validar os dados'))
    return redirect(login_url)


def login_view(request):
    form = LoginForm()

    detalhe = Post.objects.filter(
        author__id=request.user.id).order_by('-id')

    return render(request, 'login/login.html', {
        'forms': form,
        'detalhe': detalhe,
        'form_action': reverse('login:login_create')
    })


@login_required(login_url='login:login', redirect_field_name='next')
def logout_view(request):

    if not request.POST:
        return redirect(reverse('login:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('login:login'))

    logout(request)
    return redirect(reverse('login:login'))

login/templates/login/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    {% include 'login/head.html'%}
    
    <title>{% block title %} Registro | {% endblock title %} </title>
</head>
<body>
    <main class="main-content-container">

    {% block content %}

    {% endblock content %}
    
    </main>
        
</body>
</html>

login/templates/login/dashboard.html
{% load static %}

{% if request.user.is_authenticated %}

<div class="form-content form-content">
    <h1>Seus posts:</h1>
</div>

<div class="form-content form-content">
    <table id="customers">
       
        {% for detalhes in detalhe %}

            <tr>
            
              <th style="text-align: justify;" scope="row"><a href="{% url 'blog:details' detalhes.id detalhes.slug %}">{{detalhes.title}}</a></th>
                <td>
                <div class="d-flex justify-content-end mb-4">
                    <a class="btn btn-primary text-uppercase" href="{% url 'blog:edit' detalhes.pk %}">Editar post</a>
                    <a style="margin-rigth: 2rem;" class="btn btn-danger text-uppercase" id="delete" onclick="return confirm('Tem certeza que deseja deletar o post: {{detalhes.title}}')" href="{% url 'blog:delete_post' detalhes.pk %}">Deletar post</a>
                </div>
                </td>
            
        {% empty %}
            Você ainda não fez nenhum post.
            
            </tr>

      {% endfor %}
    </table>
</div>

{% endif %}

login/templates/login/form.html
{% if not request.user.is_authenticated %}

<div class="main-content container">

    <form action="{{form_action}}" method="POST">
        {%csrf_token%}

        <div class="form-content form-content-grid">

            {% for forms in forms %}

            <div class="form-group">

                <field for="{{forms.id_for_label}}">{{forms.label}}</field>

                {{forms}}

                {% if forms.help_text %}

                <p class="help-text">{{forms.help_text}}</p>
                {% endif %}

                {{forms.errors}}

            </div>

            {% endfor %}

        </div>

        <div class="form-content form-content-grid">

            <div class="form-group">

            <button type="submit">Enviar</button>
            
            </div>
        </div>
    </form>
</div>
{% endif %}

login/templates/login/head.html
{%load static%}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
    integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
    integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
    integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'global/css/styles.css' %}">
<script src="{% static 'global/js/scripts.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" 
        crossorigin="anonymous">
</script>

login/templates/login/login.html
{% extends 'login/base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}

<div class="main-content center container">

    {% if request.user.is_authenticated %}

        <h2>Login - {{request.user.username}}</h2>

    {% else %}

    <h2>Login</h2>

    {% endif %}

    {% if request.user.is_authenticated %}

    <div>

        <form class="inline-form" action="{% url 'login:logout' %}" method="POST">

            {% csrf_token %}
            <input type="hidden" name="username" value="{{request.user.username}}">
            <button class="plainetext-button" type="submit">Logout</button>

        </form>
    </div>

    <div class="form-content form-content">
        <a href="{% url 'blog:index' %}">Volte ao site</a>
    </div>
    
    {% endif %}

</div>

{% include 'login/messages.html' %}

{% include 'login/dashboard.html' %}

{% include 'login/form.html' %}

{% if not request.user.is_authenticated %}
<div class="form-content form-content">
    Não possui conta? <a href="{% url 'login:register' %}">Clique aqui</a> e cadastre-se.
</div>
<div class="form-content form-content">
    Esqueceu a senha? <a href="{% url 'password_reset' %}">Clique aqui</a>.
</div>
<div class="form-content form-content">
    Voltar ao site <a href="{% url 'blog:index' %}">aqui</a>.
</div>
{% endif %}

{% endblock content%}

login/templates/login/messages.html
{% if messages %}
<div class="main-content center container messages-container">
    {% for message in messages %}
        <div class="message {{ message.tags }}">
            {% autoescape off %}
                {{ message }}
            {% endautoescape %}
        </div>
    {% endfor %}
</div>
{% endif %}

login/templates/login/password_reset.html
{% extends 'login/base.html' %}
{% block title %}Esqueci a senha{% endblock  %}
{% block content %}
<div class="main-content center container">
<h1>Esqueceu sua senha?</h1>
</div>
{% if not request.user.is_authenticated %}

<div class="form-content form-content-grid">
    <form method="post">
		{% csrf_token %}
		<div class="form-group">
        {{ form }}
		</div>
	</div>
		<div class="form-content form-content-grid">
            <div class="form-group">
            <button type="submit">Enviar</button>
            </div>
        
    </form>

{% endif %}
{% endblock %}

login/templates/login/password_reset_complete.html
<h1>Senha alterada com sucesso!</h1>

<p>Você pode fazer login novamente <a href="{% url 'login' %}">aqui</a></p>

login/templates/login/password_reset_confirm.html
{% extends 'login/base.html' %}
{% block title %}Esqueci a senha{% endblock  %}


{% block content %}
{% if validlink %}
<div class="main-content center container">
<h1>Redefinir senha</h1>
</div>
<div class="form-content form-content-grid">
<form  method="post">
    {% csrf_token %}
    <div class="form-group">
    {{form.as_p}}
    </div>
</div>
<div class="form-content form-content-grid">
    <div class="form-group">
    <button type="submit">Enviar</button>
    </div>
</div>
</form>

{% endif %}
{% endblock content %}

login/templates/login/password_reset_done.html
{% extends 'login/base.html' %}
{% block title %}Senha alterada{% endblock  %}

{% block content %}
<div class="main-content center container">
<h1>Obrigado</h1>
</div>
<div class="main-content center container">
<p>Nos te enviamos um email com instruções para configurar sua senha, se uma conta existe com o email fornecido. Você receberá a mensagem em breve.</p>
<p>Se você não recebeu um email, por favor certifique-se que você forneceu o endereço que você está cadastrado, e verifique sua pasta de spam.</p>
</div>
<div class="form-content form-content">
<p>Voltar para o <a href="{% url 'login:login' %}">Login</a></p>
</div>
{% endblock %}

login/templates/login/register_user.html
{% extends 'login/base.html' %}


{% block content %}

<div class="main-content center container">
    <h2>Registro</h2>
</div>

{% include 'login/messages.html' %}

{% include 'login/form.html' %}

<div class="form-content form-content">
    Já possui conta? <a href="{% url 'login:login' %}">Clique aqui</a> e faça login.
</div>

{% endblock content%}

login/templates/login/template_activate_account.html
{% autoescape off %}
Olá {{user}},

Por favor, clique no link a baixo e confirme a sua conta:

http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %}
{% endautoescape %}