blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('detalhes/<int:pk>/<slug:slug>', views.detail, name="details"),
    path('post/novo/', views.post, name="new_post"),
    path('editar/post/<int:pk>', views.edit, name="edit"),
    path('filter/<int:pk>/<str:username>', views.filter, name="filter"),
    path('search/', views.search, name="search"),
    path('delete/<int:pk>', views.delete, name="delete_post"),
    path('contato/', views.contato, name="contato"),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('registro/', views.register_view, name="register"),
    path('registro/criar/', views.register_create, name="register_create"),
    path('login/', views.login_view, name="login"),
    path('login/criar/', views.login_create, name="login_create"),
    path('logout/', views.logout_view, name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
]

blog/models.py
import os
import string
from random import SystemRandom

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from PIL import Image


class Post(models.Model):

    title = models.CharField(max_length=70, verbose_name=_('Titulo'))
    sub_title = models.CharField(
        max_length=250, default='', verbose_name=_('Subtitulo'))
    text = models.TextField(verbose_name=_('Texto'))
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    cover = models.ImageField(
        upload_to='post/cover/%Y-%m-%d/', blank="True", default='',
        verbose_name=_('Imagem'))
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    @staticmethod
    def resize_image(image, new_width=800):
        image_full_path = os.path.join(settings.MEDIA_ROOT, image.name)
        image_pillow = Image.open(image_full_path)
        original_width, original_height = image_pillow.size

        if original_width <= new_width:
            image_pillow.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_image = image_pillow.resize((new_width, new_height), Image.LANCZOS)
        new_image.save(
            image_full_path,
            optimize=True,
            quality=50,
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            rand_letters = ''.join(
                SystemRandom().choices(
                    string.ascii_letters + string.digits,
                    k=5,
                )
            )
            self.slug = slugify(f'{self.title}-{rand_letters}')

        saved = super().save(*args, **kwargs)

        if self.cover:
            try:
                self.resize_image(self.cover, 840)
            except FileNotFoundError:
                ...

        return

blog/forms.py
from django import forms

from .models import Post


class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea,
                              required=True)


class PostForm(forms.ModelForm):

    class Meta:

        model = Post
        fields = ('title', 'sub_title', 'text', 'cover')

blog/views.py
from django.contrib import messages
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.core.mail import BadHeaderError, send_mail
# PERMITE USAR A CONDICIONAL 'OR' NO FILTRO DO BANCO DE DADOS
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import (get_list_or_404, get_object_or_404, redirect,
                              render)
from django.utils import timezone

from .forms import ContactForm, PostForm
from .models import Post


def contato(request):

    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            from_email = form.cleaned_data["email"]
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email,
                          ["projetodjango23@gmail.com"])
                messages.success(
                    request,  'E-mail enviado sucesso.')
            except BadHeaderError:
                return HttpResponse("Erro ao enviar sua mensagem")
            return redirect('blog:contato')
    return render(request, "blog/contact.html", {"form": form})


def index(request):
    post = Post.objects.filter(
        is_published=True).order_by('-id')

    return render(request, 'blog/index.html', {'post': post,
                                               'title': 'Home'})


def search(request):

    search = request.GET.get('search')

    result = Post.objects.filter(
        Q(title__contains=search)
        | Q(sub_title__contains=search)
        | Q(author__username__contains=search)
        | Q(author__first_name__contains=search)
        | Q(author__last_name__contains=search)
        | Q(text__contains=search)
    ).order_by('-id')

    return render(request, 'blog/search_result.html',
                  {'result': result,
                   'search': search,
                   'title': f'Pesquisa: {search}'})


def detail(request, pk, slug):
    details = get_object_or_404(Post, pk=pk, is_published=True)
    return render(request, 'blog/detail.html', {'details': details,
                                                'title': f'{details.title}'})


def post(request):

    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_at = timezone.now()
            post.author = get_user(request)
            post.save()
            return redirect('blog:index')
    else:
        form = PostForm()
    return render(request, 'blog/post.html', {'form': form})


@login_required
def edit(request, pk):
    edit = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES, instance=edit)
        if form.is_valid():
            edit = form.save(commit=False)
            edit.update_at = timezone.now()
            edit.author = get_user(request)
            edit.save()
            return redirect('blog:index')
    else:
        form = PostForm(instance=edit)

    return render(request, 'blog/post.html', {'form': form})


@login_required
def delete(request, pk):
    form = get_object_or_404(Post, pk=pk)
    titulo = form.title
    form.delete()
    messages.success(
        request,  f'Post <strong>{titulo}</strong> foi deletado com sucesso.')
    return redirect('blog:index')


def filter(request, pk, username):
    filter = get_list_or_404(Post.objects.filter(
        author__id=pk).order_by('-id'))
    return render(request, 'blog/index.html', {'post': filter,
                                               'title': f'{username} | Posts'})

blog/templates/blog/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'blog/head.html' %}
    <title> {% block title %}{{title}}{% endblock %}</title>
</head>

<body>
    {% include 'blog/menu.html' %}
   
    {% include 'blog/header.html' %}
    {% include 'blog/messages.html' %}
        {% block content %}

        {% endblock %}

    {% include 'blog/footer.html' %}
</body>

</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}


{% load static %}

{% load crispy_forms_tags %}

{% block title %}Contato{% endblock  %}

{% block content %}

<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h2>Contato</h2>
                <br>
                <div class="mb-3">
                    <form id="contactForm" method="post" >
                        {% csrf_token %}
                        <div class="form-floating">
                            
                            <label for="{{form.id_for_label}}">{{form.label}}</label>
                                {{form | crispy}}
                            </div>
                        <!-- Submit Button-->
                        <button style="margin: 5% 0px" class="btn btn-primary text-uppercase" type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% load static %}
{% block title %} {{title}} | Detalhes{% endblock %}

{% block content %}

<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7" style="text-align: justify;">

                {% autoescape off %}
                    <p >{{ details.text|linebreaksbr }}</p>
                {% endautoescape %}

                <div class="recipe-author">
                    <!-- Editar caso o post seja seu e você esteja logado -->
                    {% if request.user.username == details.author.username %}
                    <div class="d-flex justify-content-end mb-4">
                        <a class="btn btn-primary text-uppercase" href="{% url 'blog:edit' details.pk %}">Editar post</a>
                        <a style="margin-rigth: 2rem;" class="btn btn-danger text-uppercase" id="delete" onclick="return confirm('Tem certeza que deseja deletar o post: {{details.title}}')" href="{% url 'blog:delete_post' details.pk %}">Deletar post</a>
                    </div>

                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
</article>


</script>

{% endblock %}

blog/templates/blog/footer.html
{% load static %}
<footer class="border-top">
  <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <ul class="list-inline text-center">
                  <li class="list-inline-item">
                      <a href="https://www.linkedin.com/in/eduardo-ferreira-05b32a172/" target="_blank">
                          <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                          </span>
                      </a>
                  </li>
                  <li class="list-inline-item">
                      <a href="https://github.com/eduardoferreira97" target="_blank">
                          <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                          </span>
                      </a>
                  </li>
              </ul>
              <div class="small text-center text-muted fst-italic">Criado por <a href="https://www.linkedin.com/in/eduardo-ferreira-05b32a172/" target="_blank">Eduardo José</a></div>
          </div>
      </div>
  </div>
</footer>

blog/templates/blog/head.html
{% load static %}

<!-- Google fonts-->
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<!-- Font Awesome icons (free version)-->
<script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'global/css/styles-blog.css' %}">

<!-- Script HTMX -->
<script src="https://unpkg.com/htmx.org@1.8.5"></script>

<script src="{% static 'global/js/scripts-blog.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

blog/templates/blog/header.html
{% load static %}

{% if details.cover %}

<header class="masthead" style="background-image: url({{ details.cover.url }})">

    {% else %}

    <header class="masthead" style="background-image: url('{% static 'global/assets/home-bg.jpg' %}')">

        {% endif %}

        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% if not details.title %}
                    <div class="site-heading">

                        <h1>Venha conhecer </h1>
                        <span class="subheading">Um blog completo </span>
                    </div>
                    {% else %}
                    <div class="post-heading">
                        <h1>{{details.title}}</h1>
                        <span class="subheading">{{details.sub_title}}</span>

                        {% if details.author is not None %}
                        <span class="recipe-author-item">
                            Postado por
                        
                                {% if details.author.first_name %}
                                <a style="color: #fff" href="{% url 'blog:filter' details.author.id details.author.username %}">
                                    {{ details.author.first_name }} {{ details.author.last_name }}
                                </a>
                                {% else %}
                                <a style="color: #fff" href="{% url 'blog:filter' details.author.id details.author.username %}">
                                    {{details.author.username }}
                                </a>
                                {% endif %}
                        </span>
                        {% endif %}
                        <!-- Informações autor  -->
                        <span class="recipe-author-item">
                            
                            - {{ details.created_at|date:"d/m/Y" }} às {{ details.created_at|date:"H:i" }}
                        </span>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </header>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}{{title}}{% endblock  %}

{% block content %}
    
    {% include 'blog/search_form.html' %}
    
{% for posts in post %}

    {% if posts.author is not None %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'blog:details' posts.id posts.slug %}">
                        <h2 class="post-title">{{ posts.title }}</h2>
                        {% if posts.sub_title %}
                        <h3 class="post-subtitle">{{ posts.sub_title }}</h3>
                        {% endif %}
                    </a>
                    <p class="post-meta">
                        <span class="recipe-author-item">
                           
                                <i class="fas fa-user"></i>
                            {% if posts.author.first_name %}
                                Postado por <a href="{% url 'blog:filter' posts.author.id posts.author.username %}"> {{ posts.author.first_name }} {{ posts.author.last_name }}</a>
                            {% else %}
                                Postado por <a href="{% url 'blog:filter' posts.author.id posts.author.username %}">{{ posts.author.username }}</a>
                            {% endif %}
                                
                           </span>
                        <span class="recipe-author-item">
                        <i class="fas fa-calendar-alt"> </i> {{ posts.created_at|date:"d/m/Y" }} às {{ posts.created_at|date:"H:i" }}
                        </span>
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            </div>
        </div>
    </div>
{% endif %}
{% empty %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
        <h2>Não foi encontrado nenhum post 🥲</h2>
        </div>
    </div>
</div>


{% endfor %}


{% endblock  %}

blog/templates/blog/menu.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'blog:index' %}">Meu Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:index' %}">Home</a></li>
              {% if not request.user.is_authenticated %}
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login:login' %}">Login</a></li>
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login:register' %}">Cadastre-se</a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:new_post' %}">Criar post</a></li>
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login:logout' %}">Olá, {{request.user.username}}</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:contato' %}">Contato</a></li>
          </ul>
      </div>
  </div>
</nav>

blog/templates/blog/messages.html
{% if messages %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
  </svg>

<div class=" alert alert-success d-flex align-items-center" id="sucess" role="alert">
    {% for message in messages %}
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <div>
        
            {% autoescape off %}
                {{ message }}
            {% endautoescape %}
    </div>
    {% endfor %}
</div>
{% endif %}

<script>
    $("#sucess").delay(4000).slideUp(200, function() {
        $(this).alert('close');
    });
</script>

blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}

{% endblock %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Novo Post{% endblock  %}

{% block content %}

<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h2>Novo post</h2>
                <br>
                <div class="mb-3">
                    <form id="contactForm" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-floating">
                            
                            <label for="{{form.id_for_label}}">{{form.label}}</label>
                                {{form | crispy}}
                            </div>
                        <!-- Submit Button-->
                        <button style="margin: 5% 0px" class="btn btn-primary text-uppercase" type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

blog/templates/blog/search_form.html
<form style="margin: 5%;" class="d-flex" method="GET" action="{% url 'blog:search' %}">
    {% csrf_token %}
    <input id="search" name="search" class="form-control me-1" type="search" placeholder="Procure por: Título, Subtítulo, Autor ou texto" aria-label="Search" value="{{search}}">
    <button class="btn btn-outline-primary" type="submit">
        <i class="fa-solid fa-magnifying-glass"></i>
    </button>
</form>

blog/templates/blog/search_result.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}{{title}}{% endblock  %}

{% block content %}

{% include 'blog/search_form.html' %}

{% for posts in result %}

    {% if posts.author is not None %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'blog:details' posts.id posts.slug %}">
                        <h2 class="post-title">{{ posts.title }}</h2>
                        {% if posts.sub_title %}
                        <h3 class="post-subtitle">{{ posts.sub_title }}</h3>
                        {% endif %}
                    </a>
                    <p class="post-meta">
                        <span class="recipe-author-item">
                           
                                <i class="fas fa-user"></i>
                            {% if posts.author.first_name %}
                                Postado por <a href="{% url 'blog:filter' posts.author.id posts.author.username %}"> {{ posts.author.first_name }} {{ posts.author.last_name }}</a>
                            {% else %}
                                Postado por <a href="{% url 'blog:filter' posts.author.id posts.author.username %}">{{ posts.author.username }}</a>
                            {% endif %}
                                
                           </span>
                        <span class="recipe-author-item">
                        <i class="fas fa-calendar-alt"> </i> {{ posts.created_at|date:"d/m/Y" }} às {{ posts.created_at|date:"H:i" }}
                        </span>
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            </div>
        </div>
    </div>
{% endif %}
{% empty %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
        <h3>Não foi encontrado nenhum resultado 🥲</h3>
        <br>
        </div>
    </div>
</div>


{% endfor %}


{% endblock  %}

blog/templates/blog/template_contact.html
{% autoescape off %}

De {{name}}.

E-mail: {{email}}

{{message}}

{% endautoescape %}